version: "3"
services:
    frontend:
        image: vinny1892/eventfeedback-frontend
        ports:
            - 3000:3000
        deploy:
            mode: replicated
            replicas: 4
            placement:
                constraints: [node.role == worker]
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 2
                delay: 10s
                failure_action: continue
                monitor: 60s
                max_failure_ratio: 0.3
        networks:
            - feedbackevent

    backend:
        image: vinny1892/eventfeedback-backend
        ports:
            - 8080:80
        depends_on:
            - postgres
        deploy:
            mode: replicated
            replicas: 4
            placement: 
                constraints: [node.role == worker]
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 2
                delay: 10s
                failure_action: continue
                monitor: 60s
                max_failure_ratio: 0.3
        networks:
            - feedbackevent
    redis:
        image: redis
        ports:
            - 6379:6379
        deploy:
            placement:
                constraints: [node.role == manager]
        command: redis-server --requirepass seila123  --appendonly yes
        networks:
            - feedbackevent
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: "app"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "example"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - feedbackevent
networks:
    feedbackevent:
