---
- name: "Setup Machine"
  apt:
    update_cache: yes
    name:
     - nginx
     - git
     - php7.2
     - php7.2-zip
     - php7.2-pdo
     - php7.2-mbstring
     - php7.2-tokenizer
     - php7.2-xml
     - php7.2-mysqlnd
     - php7.2-opcache

- name: "Clone Repo"
  git:
    repo: https://github.com/Vinny1892/criticancia
    dest: /var/www/seila

- name: "Change Permissions"
  file:
     group: "www-data"
     owner: "www-data"
     path: "/var/www"
     recurse: yes

- name: Configure Nginx

  copy:
      src: main/nginx.conf
      dest: /etc/nginx
- name: 'Configure Nginx - pt2'
  copy:
      src: { item.source }
      dest: { item.destination }
      debug: msg=" source {{ item.source }} , destination {{ item.destination }}"
  with_items:
      - { source: "criticancia/app.conf" , destination: "/etc/nginx/conf.d/"  }
      - { source: "criticancia/php.conf" , destination: "/etc/nginx/conf.d/"  }
